#!/usr/bin/env bash
# Usage: helmfilenv version-file [<dir>]
# Summary: Detect the file that sets the current helmfilenv version
set -e
[ -n "$HELMFILENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -s "${root}/.helm-version" ]; then
      echo "${root}/.helm-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$HELMFILENV_DIR" || {
    [ "$HELMFILENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${HELMFILENV_ROOT}/version"
fi
