#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific helm version
#
# Usage: helmfilenv local <version>
#        helmfilenv local --unset
#
# Sets the local application-specific helm version by writing the
# version name to a file named `.helm-version'.
#
# When you run a helm command, helmfilenv will look for a `.helm-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, helmfilenv will use the global helm version
# specified with `helmfilenv global'. A version specified with the
# `HELMFILENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a helm version known to helmfilenv.
# The special version string `system' will use your default system helm.
# Run `helmfilenv versions' for a list of available helm versions.

set -e
[ -n "$HELMFILENV_DEBUG" ] && set -x

# Provide helmfilenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec helmfilenv-versions --bare
fi

HELMFILENV_VERSION="$1"

if [ "$HELMFILENV_VERSION" = "--unset" ]; then
  rm -f .helm-version
elif [ -n "$HELMFILENV_VERSION" ]; then
  helmfilenv-version-file-write .helm-version "$HELMFILENV_VERSION"
else
  if version_file="$(helmfilenv-version-file "$PWD")"; then
    helmfilenv-version-file-read "$version_file"
  else
    echo "helmfilenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
