#!/usr/bin/env bash
# Usage: helmfilenv completions <command> [arg1 arg2...]

set -e
[ -n "$HELMFILENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  helmfilenv-help --usage completions >&2
  exit 1
fi

# Provide helmfilenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec helmfilenv-commands
fi

COMMAND_PATH="$(command -v "helmfilenv-$COMMAND" || command -v "helmfilenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide helmfilenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
