#!/usr/bin/env bash
# Usage: helmfilenv uninstall <version>
# Summary: Uninstall the specified version of helm

[ -n "${HELMFILENV_DEBUG}" ] && set -x
source ${HELMFILENV_ROOT}/libexec/helpers.sh

[ ${#} -gt 1 ] && error_and_die "usage: helmfilenv uninstall [<version>]"

declare version

if [ -z "${1}" ]; then
  version_file="$(helmfilenv-version-file)"
  if [ "${version_file}" != "${HELMFILENV_ROOT}/version" ];then
    version="$(cat ${version_file} || true)"
  fi
else
  version="${1}"
fi

[ -n "${version}" ] || error_and_die "Version is not specified"

dst_path="${HELMFILENV_ROOT}/versions/${version}"
if [ -f "${dst_path}/helm" ]; then
  info "Uninstall helm v${version}"
  rm -r "${dst_path}"
  info "\033[0;32mhelm v${version} is successfully uninstalled\033[0;39m"
fi
