#!/usr/bin/env bash
# Usage: helmfilenv version-file-write <file> <version>

set -e
[ -n "$HELMFILENV_DEBUG" ] && set -x

HELMFILENV_VERSION_FILE="$1"
HELMFILENV_VERSION="$2"

if [ -z "$HELMFILENV_VERSION" ] || [ -z "$HELMFILENV_VERSION_FILE" ]; then
  helmfilenv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
helmfilenv-bin-path "$HELMFILENV_VERSION" > /dev/null

# Write the version out to disk.
echo "$HELMFILENV_VERSION" > "$HELMFILENV_VERSION_FILE"
