#!/usr/bin/env bash
# Summary: Show the current helm version and its origin
#
# Shows the currently selected helm version and how it was selected.
# To obtain only the version string, use `helmfilenv version-name'.

set -e
[ -n "$HELMFILENV_DEBUG" ] && set -x

echo "$(helmfilenv-version-name) (set by $(helmfilenv-version-origin))"
